- name: Install security agent on virtual machine instance
  hosts: agents
  become: true
  become_user: root
  tasks:
  - name: Create the /opt/csg_security_agent directory
    file:
      path: /opt/csg_security_agent
      state: directory

  - name: copy installer script
    copy:
      src: ./security_agent_installer_linux_amd64_v1.0.0.sh
      dest: /opt/csg_security_agent/security_agent_installer.sh
      mode: 0755

  - name: copy installer config
    copy:
      src: ./security_agent_config.conf
      dest: /opt/csg_security_agent/security_agent_config.conf
      mode: 0755

  - name: Update token in security_agent_config.conf
    replace:
      path: /opt/csg_security_agent/security_agent_config.conf
      regexp: <add_unique_token_here>
      replace: "{{ TOKEN }}"

  - name: run security agent installer
    register: out
    command: "/opt/csg_security_agent/security_agent_installer.sh --config /opt/csg_security_agent/security_agent_config.conf --token {{ TOKEN }}"

  - debug: msg="{{ out.stdout_lines }} "
